name: Release

on:
  workflow_dispatch:
    inputs:
      version:        
        description: "The version to release"
        default: "1.0.0"      
        required: true
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: false
      #     tags: robinmanuelthiel/speedtest:latest
      
      - run: |
          docker build -t robinmanuelthiel/speedtest:latest-arm32v7 --build-arg ARCH=arm32v7 .
          docker build -t robinmanuelthiel/speedtest:latest-arm64v8 --build-arg ARCH=arm64v8 .

          # docker push robinmanuelthiel/speedtest:latest-arm32v7
          # docker push robinmanuelthiel/speedtest:latest-arm64v8

          docker manifest create robinmanuelthiel/speedtest:latest \
            --amend robinmanuelthiel/speedtest:latest-arm32v7 \
            --amend robinmanuelthiel/speedtest:latest-arm64v8

          # docker manifest push robinmanuelthiel/speedtest:latest

