name: Release

on:
  workflow_dispatch:
    inputs:
      version:        
        description: "The version to release"
        default: "1.0.0"      
        required: true
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - run: docker buildx build --tag robinmanuelthiel/speedtest:latest-arm64v8 --platform linux/arm64 .
      
      - run: |
          docker buildx build --tag robinmanuelthiel/speedtest:latest-arm32v7 --platform linux/arm/v7 --build-arg ARCH=arm32v7/ .
          docker buildx build --tag robinmanuelthiel/speedtest:latest-arm64v8 --platform linux/arm64/v8 --build-arg ARCH=arm64v8/ .
          docker buildx build --tag robinmanuelthiel/speedtest:latest-amd64 --platform linux/amd64 --build-arg ARCH=amd64/ .

          docker manifest create robinmanuelthiel/speedtest:latest \
            --amend robinmanuelthiel/speedtest:latest-arm32v7 \
            --amend robinmanuelthiel/speedtest:latest-arm64v8 \
            --amend robinmanuelthiel/speedtest:latest-amd64

          # docker manifest push robinmanuelthiel/speedtest:latest

